
name: esmfold
channels:
  - conda-forge
  - bioconda
  - pytorch
dependencies:
  - conda-forge::python=3.7
  - conda-forge::setuptools=59.5.0
  - conda-forge::pip
  # - conda-forge::cudatoolkit==11.3.* # Needed for esm
  # - pytorch::pytorch=1.12.*

  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu113
      - torch==1.12.1+cu113 
      - numpy==1.21.2
      - requests==2.26.0
      - tqdm==4.62.2
      - fair-esm[esmfold]
      - mkl==2024.0
